leagues = [
    { name: 'Primal League',
      country: 'England',
      time_zone: 'London' },
    { name: 'Japan League',
      country: 'Japan',
      time_zone: 'Tokyo' },
]

leagues.each { |league| League.create!(league) }

clubs = [
    { name: "Bulls FC",
      established_on: "1894",
      hometown: "London",
      country: "England",
      manager: "Melina Larson",
      league: League.find_by!(name: 'Primal League') },
    { name: "Leon FC",
      established_on: "1910",
      hometown: "Liverpool",
      country: "England",
      manager: "Shanti Wolf",
      league: League.find_by!(name: 'Primal League') },
    { name: "Birmingham United FC",
      established_on: "1890",
      hometown: "Birmingham",
      country: "England",
      manager: "Jordon Ryan",
      league: League.find_by!(name: 'Primal League') },
    { name: "Manchester Town FC",
      established_on: "1902",
      hometown: "Manchester",
      country: "England",
      manager: "Nicky Walsh",
      league: League.find_by!(name: 'Primal League') },
    { name: "Yokohama Bayside FC",
      established_on: "1989",
      hometown: "Yokohama",
      country: "Japan",
      manager: "Takuya Kuroda",
      league: League.find_by!(name: 'Japan League') },
    { name: "Tokyo City FC",
      established_on: "1981",
      hometown: "Tokyo",
      country: "Japan",
      manager: "Shota Yamashita",
      league: League.find_by!(name: 'Japan League') },
    { name: "FC Nagano",
      established_on: "1991",
      hometown: "Nagano",
      country: "Japan",
      manager: "Floyd Turner",
      league: League.find_by!(name: 'Japan League') },
    { name: "Saitama FC",
      established_on: "1991",
      hometown: "Saitama",
      country: "Japan",
      manager: "Tsuyoshi Suzuki",
      league: League.find_by!(name: 'Japan League') }
]

clubs.each do |club|
  created_club = Club.find_or_create_by!(club)
  created_club.logo.attach(io: File.open("./lib/assets/logos/logo_#{created_club.name.gsub(' ', '').underscore}.png"), filename: "logo_#{created_club.name.sub(' ', '').underscore}.png", content_type: "image/png")
end

# /lib/generate_sample_players.rb を実行して得られた配列をコピペしている。詳しくは該当ファイル参照のこと
players = [
  { firstname: 'Otto', lastname: 'Kohler', position: 'FW', country: 'Spain', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Bulls FC') },
  { firstname: 'Leo', lastname: 'Mitchell', position: 'FW', country: 'Spain', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Bulls FC') },
  { firstname: 'Nolan', lastname: 'Cruickshank', position: 'FW', country: 'Spain', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Bulls FC') },
  { firstname: 'Luciano', lastname: 'Mertz', position: 'MF', country: 'Spain', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Bulls FC') },
  { firstname: 'Rafael', lastname: 'Nicolas', position: 'MF', country: 'Brazil', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Bulls FC') },
  { firstname: 'Landon', lastname: 'Monahan', position: 'MF', country: 'Italy', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Bulls FC') },
  { firstname: 'Wiley', lastname: 'Goyette', position: 'MF', country: 'England', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Bulls FC') },
  { firstname: 'Stan', lastname: 'Fay', position: 'MF', country: 'Belgium', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Bulls FC') },
  { firstname: 'Karl', lastname: 'Hilll', position: 'MF', country: 'Argentina', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Bulls FC') },
  { firstname: 'Dick', lastname: 'Ledner', position: 'MF', country: 'Spain', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Bulls FC') },
  { firstname: 'Darron', lastname: 'Greenfelder', position: 'DF', country: 'Argentina', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Bulls FC') },
  { firstname: 'Gilbert', lastname: 'Kreiger', position: 'DF', country: 'Spain', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Bulls FC') },
  { firstname: 'Jermaine', lastname: 'McGlynn', position: 'DF', country: 'Portugal', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Bulls FC') },
  { firstname: 'Giovanni', lastname: 'Howell', position: 'DF', country: 'Portugal', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Bulls FC') },
  { firstname: 'Esteban', lastname: 'Gottlieb', position: 'DF', country: 'Portugal', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Bulls FC') },
  { firstname: 'Carlos', lastname: 'Ziemann', position: 'DF', country: 'Belgium', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Bulls FC') },
  { firstname: 'Taro', lastname: 'Tanaka', position: 'GK', country: 'Japan', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Bulls FC') },
  { firstname: 'Robert', lastname: 'Cassin', position: 'GK', country: 'Senegal', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Bulls FC') },
  { firstname: 'Elvin', lastname: 'Waters', position: 'GK', country: 'Belgium', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Bulls FC') },

  { firstname: 'Anderson', lastname: 'Shanahan', position: 'FW', country: 'Portugal', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Leon FC') },
  { firstname: 'Marcos', lastname: 'Corwin', position: 'FW', country: 'Argentina', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Leon FC') },
  { firstname: 'Louis', lastname: 'Morissette', position: 'FW', country: 'Brazil', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Leon FC') },
  { firstname: 'Byron', lastname: 'Dietrich', position: 'MF', country: 'France', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Leon FC') },
  { firstname: 'Minamino', lastname: 'Takuma', position: 'MF', country: 'Japan', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Leon FC') },
  { firstname: 'Ezra', lastname: 'Stiedemann', position: 'MF', country: 'Argentina', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Leon FC') },
  { firstname: 'Adolfo', lastname: 'Brakus', position: 'MF', country: 'France', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Leon FC') },
  { firstname: 'Bernardo', lastname: 'Lehner', position: 'MF', country: 'Belgium', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Leon FC') },
  { firstname: 'Broderick', lastname: 'Dooley', position: 'MF', country: 'Germany', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Leon FC') },
  { firstname: 'Elmo', lastname: 'Pagac', position: 'MF', country: 'Brazil', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Leon FC') },
  { firstname: 'Adolph', lastname: 'Hilll', position: 'DF', country: 'Netherlands', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Leon FC') },
  { firstname: 'Antoine', lastname: 'Watsica', position: 'DF', country: 'Brazil', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Leon FC') },
  { firstname: 'Valentine', lastname: 'Bogisich', position: 'DF', country: 'Brazil', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Leon FC') },
  { firstname: 'Yuto', lastname: 'Tomonaga', position: 'DF', country: 'Japan', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Leon FC') },
  { firstname: 'Denver', lastname: 'Gottlieb', position: 'DF', country: 'Germany', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Leon FC') },
  { firstname: 'Masaki', lastname: 'Yoshida', position: 'DF', country: 'Japan', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Leon FC') },
  { firstname: 'Sylvester', lastname: 'Johns', position: 'GK', country: 'Senegal', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Leon FC') },
  { firstname: 'Jackie', lastname: 'Dietrich', position: 'GK', country: 'Germany', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Leon FC') },
  { firstname: 'Ambrose', lastname: 'Schroeder', position: 'GK', country: 'France', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Leon FC') },

  { firstname: 'Kent', lastname: 'Hahn', position: 'FW', country: 'Argeria', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Birmingham United FC') },
  { firstname: 'Edmond', lastname: 'Stracke', position: 'FW', country: 'Netherlands', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Birmingham United FC') },
  { firstname: 'Rolando', lastname: 'Rippin', position: 'FW', country: 'Germany', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Birmingham United FC') },
  { firstname: 'Byron', lastname: 'Anderson', position: 'MF', country: 'Argentina', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Birmingham United FC') },
  { firstname: 'Mckinley', lastname: 'Lesch', position: 'MF', country: 'Brazil', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Birmingham United FC') },
  { firstname: 'Forrest', lastname: 'Dietrich', position: 'MF', country: 'Belgium', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Birmingham United FC') },
  { firstname: 'Jules', lastname: 'Schiller', position: 'MF', country: 'Portugal', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Birmingham United FC') },
  { firstname: 'Hiroki', lastname: 'Sakui', position: 'MF', country: 'Japan', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Birmingham United FC') },
  { firstname: 'Al', lastname: 'Kemmer', position: 'MF', country: 'Netherlands', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Birmingham United FC') },
  { firstname: 'Fabian', lastname: 'Walker', position: 'MF', country: 'Spain', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Birmingham United FC') },
  { firstname: 'Tyrone', lastname: 'Leannon', position: 'DF', country: 'Argentina', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Birmingham United FC') },
  { firstname: 'Kai', lastname: 'Itakura', position: 'DF', country: 'Japan', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Birmingham United FC') },
  { firstname: 'Hong', lastname: 'Mosciski', position: 'DF', country: 'France', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Birmingham United FC') },
  { firstname: 'Warren', lastname: 'Watsica', position: 'DF', country: 'Brazil', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Birmingham United FC') },
  { firstname: 'Reuben', lastname: 'Jakubowski', position: 'DF', country: 'Brazil', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Birmingham United FC') },
  { firstname: 'Terence', lastname: 'Rice', position: 'DF', country: 'Portugal', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Birmingham United FC') },
  { firstname: 'Brock', lastname: 'Schroeder', position: 'GK', country: 'Argentina', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Birmingham United FC') },
  { firstname: 'Raphael', lastname: 'Leffler', position: 'GK', country: 'France', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Birmingham United FC') },
  { firstname: 'Yoshikatsu', lastname: 'Kawasaki', position: 'GK', country: 'Japan', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Birmingham United FC') },

  { firstname: 'Rudolph', lastname: 'Swaniawski', position: 'FW', country: 'Belgium', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Manchester Town FC') },
  { firstname: 'Ruben', lastname: 'Leannon', position: 'FW', country: 'Portugal', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Manchester Town FC') },
  { firstname: 'Rolland', lastname: 'Hermann', position: 'FW', country: 'Netherlands', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Manchester Town FC') },
  { firstname: 'Dillon', lastname: 'Hegmann', position: 'MF', country: 'Argeria', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Manchester Town FC') },
  { firstname: 'Adolfo', lastname: 'McKenzie', position: 'MF', country: 'Brazil', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Manchester Town FC') },
  { firstname: 'Minh', lastname: 'Boyer', position: 'MF', country: 'Italy', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Manchester Town FC') },
  { firstname: 'Marvin', lastname: 'Hamill', position: 'MF', country: 'Netherlands', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Manchester Town FC') },
  { firstname: 'Deandre', lastname: 'Runolfsdottir', position: 'MF', country: 'Argeria', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Manchester Town FC') },
  { firstname: 'Forrest', lastname: 'Lakin', position: 'MF', country: 'Japan', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Manchester Town FC') },
  { firstname: 'Shinsuke', lastname: 'Kagaya', position: 'MF', country: 'Japan', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Manchester Town FC') },
  { firstname: 'Gregorio', lastname: 'Witting', position: 'DF', country: 'Spain', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Manchester Town FC') },
  { firstname: 'Irvin', lastname: 'Becker', position: 'DF', country: 'Italy', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Manchester Town FC') },
  { firstname: 'Kevin', lastname: 'Spencer', position: 'DF', country: 'Brazil', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Manchester Town FC') },
  { firstname: 'Danny', lastname: 'Ziemann', position: 'DF', country: 'Germany', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Manchester Town FC') },
  { firstname: 'Edgar', lastname: 'Reilly', position: 'DF', country: 'Germany', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Manchester Town FC') },
  { firstname: 'Zane', lastname: 'Raynor', position: 'DF', country: 'Argentina', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Manchester Town FC') },
  { firstname: 'Wilmer', lastname: 'Jakubowski', position: 'GK', country: 'Germany', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Manchester Town FC') },
  { firstname: 'Emerson', lastname: 'Romaguera', position: 'GK', country: 'Italy', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Manchester Town FC') },
  { firstname: 'Laverne', lastname: 'Bauch', position: 'GK', country: 'Argeria', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Manchester Town FC') },

  { firstname: 'Koumei', lastname: 'Ono', position: 'FW', country: 'Japan', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Yokohama Bayside FC') },
  { firstname: 'Tomoki', lastname: 'Saitou', position: 'FW', country: 'Japan', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Yokohama Bayside FC') },
  { firstname: 'Mizuki', lastname: 'Takeda', position: 'FW', country: 'Japan', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Yokohama Bayside FC') },
  { firstname: 'Kotarou', lastname: 'Matsushima', position: 'MF', country: 'Japan', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Yokohama Bayside FC') },
  { firstname: 'Toshihide', lastname: 'Hashimoto', position: 'MF', country: 'Japan', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Yokohama Bayside FC') },
  { firstname: 'Hideo', lastname: 'Takemoto', position: 'MF', country: 'Japan', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Yokohama Bayside FC') },
  { firstname: 'Ryuuji', lastname: 'Hirano', position: 'MF', country: 'Japan', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Yokohama Bayside FC') },
  { firstname: 'Kouichi', lastname: 'Arai', position: 'MF', country: 'Japan', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Yokohama Bayside FC') },
  { firstname: 'Masanori', lastname: 'Tsuruta', position: 'MF', country: 'Japan', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Yokohama Bayside FC') },
  { firstname: 'Yuusei', lastname: 'Ueda', position: 'MF', country: 'Japan', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Yokohama Bayside FC') },
  { firstname: 'Toshihiko', lastname: 'Nonaka', position: 'DF', country: 'Japan', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Yokohama Bayside FC') },
  { firstname: 'Ten', lastname: 'Narita', position: 'DF', country: 'Japan', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Yokohama Bayside FC') },
  { firstname: 'Norio', lastname: 'Hoshino', position: 'DF', country: 'Japan', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Yokohama Bayside FC') },
  { firstname: 'Youki', lastname: 'Okazaki', position: 'DF', country: 'Japan', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Yokohama Bayside FC') },
  { firstname: 'Shougo', lastname: 'Yajima', position: 'DF', country: 'Japan', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Yokohama Bayside FC') },
  { firstname: 'Yoshinari', lastname: 'Ozawa', position: 'DF', country: 'Japan', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Yokohama Bayside FC') },
  { firstname: 'Ryouhei', lastname: 'Kubota', position: 'GK', country: 'Japan', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Yokohama Bayside FC') },
  { firstname: 'Atsushi', lastname: 'Kawasaki', position: 'GK', country: 'Japan', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Yokohama Bayside FC') },
  { firstname: 'Kouji', lastname: 'Ooyama', position: 'GK', country: 'Japan', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Yokohama Bayside FC') },

  { firstname: 'Hideki', lastname: 'Tsuda', position: 'FW', country: 'Japan', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Tokyo City FC') },
  { firstname: 'Souta', lastname: 'Matsuda', position: 'FW', country: 'Japan', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Tokyo City FC') },
  { firstname: 'Senri', lastname: 'Nishikawa', position: 'FW', country: 'Japan', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Tokyo City FC') },
  { firstname: 'Kazuki', lastname: 'Taguchi', position: 'MF', country: 'Japan', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Tokyo City FC') },
  { firstname: 'Tomu', lastname: 'Fukushima', position: 'MF', country: 'Japan', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Tokyo City FC') },
  { firstname: 'Wataru', lastname: 'Takai', position: 'MF', country: 'Japan', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Tokyo City FC') },
  { firstname: 'Yuuta', lastname: 'Takahashi', position: 'MF', country: 'Japan', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Tokyo City FC') },
  { firstname: 'Daisuke', lastname: 'Kawasaki', position: 'MF', country: 'Japan', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Tokyo City FC') },
  { firstname: 'Souta', lastname: 'Takizawa', position: 'MF', country: 'Japan', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Tokyo City FC') },
  { firstname: 'Yuutarou', lastname: 'Nishi', position: 'MF', country: 'Japan', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Tokyo City FC') },
  { firstname: 'Yuuma', lastname: 'Aoyagi', position: 'DF', country: 'Japan', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Tokyo City FC') },
  { firstname: 'Ryuuji', lastname: 'Yoshii', position: 'DF', country: 'Japan', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Tokyo City FC') },
  { firstname: 'Yuuta', lastname: 'Toyoda', position: 'DF', country: 'Japan', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Tokyo City FC') },
  { firstname: 'Tetsuo', lastname: 'Kanai', position: 'DF', country: 'Japan', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Tokyo City FC') },
  { firstname: 'Naohisa', lastname: 'Kawamura', position: 'DF', country: 'Japan', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Tokyo City FC') },
  { firstname: 'Yamato', lastname: 'Takeuchi', position: 'DF', country: 'Japan', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Tokyo City FC') },
  { firstname: 'Toshikatsu', lastname: 'Takagi', position: 'GK', country: 'Japan', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Tokyo City FC') },
  { firstname: 'Kyouichi', lastname: 'Sekine', position: 'GK', country: 'Japan', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Tokyo City FC') },
  { firstname: 'Kenji', lastname: 'Shouji', position: 'GK', country: 'Japan', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Tokyo City FC') },

  { firstname: 'Tomeharu', lastname: 'Matsunaga', position: 'FW', country: 'Japan', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'FC Nagano') },
  { firstname: 'Naohiro', lastname: 'Shinozaki', position: 'FW', country: 'Japan', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'FC Nagano') },
  { firstname: 'Ikkou', lastname: 'Sugiyama', position: 'FW', country: 'Japan', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'FC Nagano') },
  { firstname: 'Hiyuu', lastname: 'Watanabe', position: 'MF', country: 'Japan', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'FC Nagano') },
  { firstname: 'Naohisa', lastname: 'Ninomiya', position: 'MF', country: 'Japan', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'FC Nagano') },
  { firstname: 'Kentarou', lastname: 'Usui', position: 'MF', country: 'Japan', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'FC Nagano') },
  { firstname: 'Masatoshi', lastname: 'Matsunaga', position: 'MF', country: 'Japan', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'FC Nagano') },
  { firstname: 'Rintarou', lastname: 'Sakaguchi', position: 'MF', country: 'Japan', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'FC Nagano') },
  { firstname: 'Kazunari', lastname: 'Tada', position: 'MF', country: 'Japan', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'FC Nagano') },
  { firstname: 'Kousei', lastname: 'Matsumoto', position: 'MF', country: 'Japan', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'FC Nagano') },
  { firstname: 'Katsunori', lastname: 'Imano', position: 'DF', country: 'Japan', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'FC Nagano') },
  { firstname: 'Aito', lastname: 'Kubo', position: 'DF', country: 'Japan', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'FC Nagano') },
  { firstname: 'Takahiro', lastname: 'Nishino', position: 'DF', country: 'Japan', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'FC Nagano') },
  { firstname: 'Shinji', lastname: 'Baba', position: 'DF', country: 'Japan', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'FC Nagano') },
  { firstname: 'Yasutaka', lastname: 'Kishi', position: 'DF', country: 'Japan', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'FC Nagano') },
  { firstname: 'Kaito', lastname: 'Wada', position: 'DF', country: 'Japan', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'FC Nagano') },
  { firstname: 'Kenichi', lastname: 'Honda', position: 'GK', country: 'Japan', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'FC Nagano') },
  { firstname: 'Toshiyuki', lastname: 'Yokawa', position: 'GK', country: 'Japan', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'FC Nagano') },
  { firstname: 'Tomoki', lastname: 'Adachi', position: 'GK', country: 'Japan', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'FC Nagano') },

  { firstname: 'Tomeharu', lastname: 'Matsunaga', position: 'FW', country: 'Japan', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Saitama FC') },
  { firstname: 'Naohiro', lastname: 'Shinozaki', position: 'FW', country: 'Japan', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Saitama FC') },
  { firstname: 'Ikkou', lastname: 'Sugiyama', position: 'FW', country: 'Japan', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Saitama FC') },
  { firstname: 'Hiyuu', lastname: 'Watanabe', position: 'MF', country: 'Japan', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Saitama FC') },
  { firstname: 'Naohisa', lastname: 'Ninomiya', position: 'MF', country: 'Japan', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Saitama FC') },
  { firstname: 'Kentarou', lastname: 'Usui', position: 'MF', country: 'Japan', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Saitama FC') },
  { firstname: 'Masatoshi', lastname: 'Matsunaga', position: 'MF', country: 'Japan', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Saitama FC') },
  { firstname: 'Rintarou', lastname: 'Sakaguchi', position: 'MF', country: 'Japan', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Saitama FC') },
  { firstname: 'Kazunari', lastname: 'Tada', position: 'MF', country: 'Japan', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Saitama FC') },
  { firstname: 'Kousei', lastname: 'Matsumoto', position: 'MF', country: 'Japan', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Saitama FC') },
  { firstname: 'Katsunori', lastname: 'Imano', position: 'DF', country: 'Japan', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Saitama FC') },
  { firstname: 'Aito', lastname: 'Kubo', position: 'DF', country: 'Japan', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Saitama FC') },
  { firstname: 'Takahiro', lastname: 'Nishino', position: 'DF', country: 'Japan', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Saitama FC') },
  { firstname: 'Shinji', lastname: 'Baba', position: 'DF', country: 'Japan', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Saitama FC') },
  { firstname: 'Yasutaka', lastname: 'Kishi', position: 'DF', country: 'Japan', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Saitama FC') },
  { firstname: 'Kaito', lastname: 'Wada', position: 'DF', country: 'Japan', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Saitama FC') },
  { firstname: 'Kenichi', lastname: 'Honda', position: 'GK', country: 'Japan', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Saitama FC') },
  { firstname: 'Toshiyuki', lastname: 'Yokawa', position: 'GK', country: 'Japan', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Saitama FC') },
  { firstname: 'Tomoki', lastname: 'Adachi', position: 'GK', country: 'Japan', birthday: Random.rand(Date.new(1984, 1, 1)...Date.new(2002, 12, 31)), club: Club.find_by(name: 'Saitama FC') },
]

players.each { |player| Player.find_or_create_by!(player) }

Time.zone = 'London'
matches = []
matches_in_england = [
  { kicked_off_at: Time.zone.local(Date.current.year - 1, 8, 1, 12, 30), league: League.find_by!(name: 'Primal League'), home_team: Club.find_by!(name: 'Bulls FC'), away_team: Club.find_by!(name: 'Leon FC'), home_team_score: 3, away_team_score: 2 },
  { kicked_off_at: Time.zone.local(Date.current.year - 1, 8, 1, 14, 00), league: League.find_by!(name: 'Primal League'), home_team: Club.find_by!(name: 'Birmingham United FC'), away_team: Club.find_by!(name: 'Manchester Town FC'), home_team_score: 1, away_team_score: 3 },
  { kicked_off_at: Time.zone.local(Date.current.year - 1, 8, 7, 19, 30), league: League.find_by!(name: 'Primal League'), home_team: Club.find_by!(name: 'Leon FC'), away_team: Club.find_by!(name: 'Birmingham United FC'), home_team_score: 0, away_team_score: 0 },
  { kicked_off_at: Time.zone.local(Date.current.year - 1, 8, 8, 20, 00), league: League.find_by!(name: 'Primal League'), home_team: Club.find_by!(name: 'Manchester Town FC'), away_team: Club.find_by!(name: 'Bulls FC'), home_team_score: 4, away_team_score: 3 },
  { kicked_off_at: Time.zone.local(Date.current.year - 1, 8, 14, 12, 30), league: League.find_by!(name: 'Primal League'), home_team: Club.find_by!(name: 'Birmingham United FC'), away_team: Club.find_by!(name: 'Bulls FC'), home_team_score: 3, away_team_score: 2 },
  { kicked_off_at: Time.zone.local(Date.current.year - 1, 8, 14, 14, 00), league: League.find_by!(name: 'Primal League'), home_team: Club.find_by!(name: 'Leon FC'), away_team: Club.find_by!(name: 'Manchester Town FC'), home_team_score: 1, away_team_score: 0 },
  { kicked_off_at: Time.zone.local(Date.current.year - 1, 8, 21, 12, 30), league: League.find_by!(name: 'Primal League'), home_team: Club.find_by!(name: 'Leon FC'), away_team: Club.find_by!(name: 'Bulls FC' ), home_team_score: 3, away_team_score: 0 },
  { kicked_off_at: Time.zone.local(Date.current.year - 1, 8, 21, 14, 00), league: League.find_by!(name: 'Primal League'), home_team: Club.find_by!(name: 'Manchester Town FC'), away_team: Club.find_by!(name: 'Birmingham United FC'), home_team_score: 1, away_team_score: 1 },
  { kicked_off_at: Time.zone.local(Date.current.year - 1, 8, 28, 19, 30), league: League.find_by!(name: 'Primal League'), home_team: Club.find_by!(name: 'Birmingham United FC'), away_team: Club.find_by!(name: 'Leon FC'), home_team_score: 0, away_team_score: 2 },
  { kicked_off_at: Time.zone.local(Date.current.year - 1, 8, 28, 20, 00), league: League.find_by!(name: 'Primal League'), home_team: Club.find_by!(name: 'Bulls FC'), away_team: Club.find_by!(name: 'Manchester Town FC'), home_team_score: 4, away_team_score: 0 },
  { kicked_off_at: Time.zone.local(Date.current.year - 1, 9, 4, 12, 30), league: League.find_by!(name: 'Primal League'), home_team: Club.find_by!(name: 'Bulls FC'), away_team: Club.find_by!(name: 'Birmingham United FC'), home_team_score: 3, away_team_score: 2 },
  { kicked_off_at: Time.zone.local(Date.current.year - 1, 9, 4, 14, 00), league: League.find_by!(name: 'Primal League'), home_team: Club.find_by!(name: 'Manchester Town FC'), away_team: Club.find_by!(name: 'Leon FC'), home_team_score: 1, away_team_score: 2 },
]

Time.zone = 'Japan'
matches_in_japan = [
  { kicked_off_at: Time.zone.local(Date.current.year - 1, 8, 1, 12, 30), league: League.find_by!(name: 'Japan League'), home_team: Club.find_by!(name: 'Yokohama Bayside FC'), away_team: Club.find_by!(name: 'Tokyo City FC'), home_team_score: 3, away_team_score: 1 },
  { kicked_off_at: Time.zone.local(Date.current.year - 1, 8, 1, 14, 00), league: League.find_by!(name: 'Japan League'), home_team: Club.find_by!(name: 'FC Nagano'), away_team: Club.find_by!(name: 'Saitama FC'), home_team_score: 1, away_team_score: 2 },
  { kicked_off_at: Time.zone.local(Date.current.year - 1, 8, 7, 19, 30), league: League.find_by!(name: 'Japan League'), home_team: Club.find_by!(name: 'Tokyo City FC'), away_team: Club.find_by!(name: 'FC Nagano'), home_team_score: 0, away_team_score: 1 },
  { kicked_off_at: Time.zone.local(Date.current.year - 1, 8, 8, 20, 00), league: League.find_by!(name: 'Japan League'), home_team: Club.find_by!(name: 'Saitama FC'), away_team: Club.find_by!(name: 'Yokohama Bayside FC'), home_team_score: 4, away_team_score: 0 },
  { kicked_off_at: Time.zone.local(Date.current.year - 1, 8, 14, 12, 30), league: League.find_by!(name: 'Japan League'), home_team: Club.find_by!(name: 'FC Nagano'), away_team: Club.find_by!(name: 'Yokohama Bayside FC'), home_team_score: 3, away_team_score: 0 },
  { kicked_off_at: Time.zone.local(Date.current.year - 1, 8, 14, 14, 00), league: League.find_by!(name: 'Japan League'), home_team: Club.find_by!(name: 'Tokyo City FC'), away_team: Club.find_by!(name: 'Saitama FC'), home_team_score: 1, away_team_score: 3 },
  { kicked_off_at: Time.zone.local(Date.current.year - 1, 8, 21, 12, 30), league: League.find_by!(name: 'Japan League'), home_team: Club.find_by!(name: 'Tokyo City FC'), away_team: Club.find_by!(name: 'Yokohama Bayside FC' ), home_team_score: 3, away_team_score: 2 },
  { kicked_off_at: Time.zone.local(Date.current.year - 1, 8, 21, 14, 00), league: League.find_by!(name: 'Japan League'), home_team: Club.find_by!(name: 'Saitama FC'), away_team: Club.find_by!(name: 'FC Nagano'), home_team_score: 1, away_team_score: 2 },
  { kicked_off_at: Time.zone.local(Date.current.year - 1, 8, 28, 19, 30), league: League.find_by!(name: 'Japan League'), home_team: Club.find_by!(name: 'FC Nagano'), away_team: Club.find_by!(name: 'Tokyo City FC'), home_team_score: 0, away_team_score: 1 },
  { kicked_off_at: Time.zone.local(Date.current.year - 1, 8, 28, 20, 00), league: League.find_by!(name: 'Japan League'), home_team: Club.find_by!(name: 'Yokohama Bayside FC'), away_team: Club.find_by!(name: 'Saitama FC'), home_team_score: 4, away_team_score: 1 },
  { kicked_off_at: Time.zone.local(Date.current.year - 1, 9, 4, 12, 30), league: League.find_by!(name: 'Japan League'), home_team: Club.find_by!(name: 'Yokohama Bayside FC'), away_team: Club.find_by!(name: 'FC Nagano'), home_team_score: 3, away_team_score: 3 },
  { kicked_off_at: Time.zone.local(Date.current.year - 1, 9, 4, 14, 00), league: League.find_by!(name: 'Japan League'), home_team: Club.find_by!(name: 'Saitama FC'), away_team: Club.find_by!(name: 'Tokyo City FC'), home_team_score: 1, away_team_score: 0 },
]

matches_in_england.each { |match| Match.find_or_create_by!(match) }
matches_in_japan.each { |match| Match.find_or_create_by!(match) }
